[package]
name = "h3-c"
version = "C interface for the hexagonal hierarchical geospatial indexing system"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
